-- Migration 0001: initial D1 schema for zhouyi.
-- Generated by drizzle-kit; do not edit by hand without re-running
-- `npm run db:generate` and checking the diff.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id              TEXT PRIMARY KEY,
  email           TEXT NOT NULL UNIQUE,
  password_hash   TEXT NOT NULL,
  nickname       TEXT,
  region         TEXT,
  timezone       TEXT,
  last_seen_at    INTEGER NOT NULL,
  visit_count     INTEGER NOT NULL DEFAULT 1,
  user_agent      TEXT NOT NULL DEFAULT '',
  accept_language TEXT NOT NULL DEFAULT '',
  first_referer   TEXT,
  last_referer    TEXT,
  ip_address      TEXT NOT NULL DEFAULT '',
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS users_email_idx     ON users (email);
CREATE INDEX IF NOT EXISTS users_last_seen_idx ON users (last_seen_at);

CREATE TABLE IF NOT EXISTS records (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  type                TEXT NOT NULL,
  question            TEXT,
  numbers_json        TEXT,
  region              TEXT,
  timezone            TEXT,
  main_hexagram_id    INTEGER NOT NULL,
  moving_line         INTEGER NOT NULL,
  changed_hexagram_id INTEGER NOT NULL,
  ai_interpretation   TEXT,
  user_note           TEXT,
  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS records_user_created_idx ON records (user_id, created_at);
CREATE INDEX IF NOT EXISTS records_user_type_idx    ON records (user_id, type);

CREATE TABLE IF NOT EXISTS favorite_hexagrams (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  hexagram_id INTEGER NOT NULL,
  note        TEXT,
  created_at  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS fav_user_hex_idx ON favorite_hexagrams (user_id, hexagram_id);

CREATE TABLE IF NOT EXISTS ai_usage (
  id          TEXT PRIMARY KEY,
  user_id     TEXT REFERENCES users (id) ON DELETE SET NULL,
  ip_address  TEXT NOT NULL,
  date        TEXT NOT NULL,
  hexagram_id INTEGER,
  tokens_used INTEGER,
  created_at  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS ai_usage_ip_date_idx  ON ai_usage (ip_address, date);
CREATE INDEX IF NOT EXISTS ai_usage_user_date_idx ON ai_usage (user_id, date);

CREATE TABLE IF NOT EXISTS sessions (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  refresh_token_hash  TEXT NOT NULL,
  expires_at          INTEGER NOT NULL,
  created_at          INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_user_idx   ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_refresh_idx ON sessions (refresh_token_hash);

CREATE TABLE IF NOT EXISTS shared_posts (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  main_hexagram_id    INTEGER NOT NULL,
  changed_hexagram_id INTEGER NOT NULL,
  moving_line         INTEGER NOT NULL,
  question            TEXT,
  ai_summary          TEXT,
  note                TEXT,
  reply_count         INTEGER NOT NULL DEFAULT 0,
  created_at          INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS shared_posts_created_idx ON shared_posts (created_at);
CREATE INDEX IF NOT EXISTS shared_posts_user_idx    ON shared_posts (user_id);

CREATE TABLE IF NOT EXISTS shared_replies (
  id         TEXT PRIMARY KEY,
  post_id    TEXT NOT NULL REFERENCES shared_posts (id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  content    TEXT NOT NULL,
  created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS shared_replies_post_created_idx ON shared_replies (post_id, created_at);
CREATE INDEX IF NOT EXISTS shared_replies_user_idx        ON shared_replies (user_id);
